-- INSERT FASE ONE

-- STATE
INSERT INTO STATE (description, name, group_key) VALUES ("IN USE", "ACTIVE", "GENERIC");
INSERT INTO STATE (description, name, group_key) VALUES ("PAUSE", "PAUSE", "GENERIC");
INSERT INTO STATE (description, name, group_key) VALUES ("NO USE", "DELETE", "GENERIC");

-- ROL 
INSERT INTO ROLE(DESCRIPTION, NAME, STATE_ID) VALUES ('CAN DO ALL', 'ADMIN', 1);
INSERT INTO ROLE(DESCRIPTION, NAME, STATE_ID) VALUES ('DO SOMETHING', 'USER', 1);